[workspace]
members = [
  "gd32vf103xx-hal",
  "longan-nano",
  "blackbox"
]

[profile.release]
opt-level = "z"  # Optimize for size.
codegen-units = 1
lto = true

[profile.dev]
opt-level = "z"  # Optimize for size.