/// This file is autogenerated

pub const WIDTH: u32 = 95;
pub const HEIGHT: u32 = 26;

pub const LOOK_R: &[u8] = include_bytes!("LOOK_R");
pub const LOOK_L: &[u8] = include_bytes!("LOOK_L");
pub const SLEEP: &[u8] = include_bytes!("SLEEP");
pub const SLEEP2: &[u8] = include_bytes!("SLEEP2");
pub const AWAKE: &[u8] = include_bytes!("AWAKE");
pub const BORED: &[u8] = include_bytes!("BORED");
pub const INTENSE: &[u8] = include_bytes!("INTENSE");
pub const COOL: &[u8] = include_bytes!("COOL");
pub const HAPPY: &[u8] = include_bytes!("HAPPY");
pub const EXCITED: &[u8] = include_bytes!("EXCITED");
pub const SMART: &[u8] = include_bytes!("SMART");
pub const LONELY: &[u8] = include_bytes!("LONELY");
pub const SAD: &[u8] = include_bytes!("SAD");
pub const ANGRY: &[u8] = include_bytes!("ANGRY");
pub const FRIEND: &[u8] = include_bytes!("FRIEND");
pub const BROKEN: &[u8] = include_bytes!("BROKEN");
pub const DEBUG: &[u8] = include_bytes!("DEBUG");
