from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

LOOK_R = '( ⚆_⚆)'
LOOK_L = '(☉_☉ )'
LOOK_R_HAPPY = '( ◕‿◕)'
LOOK_L_HAPPY = '(◕‿◕ )'
SLEEP = '(⇀‿‿↼)'
SLEEP2 = '(≖‿‿≖)'
AWAKE = '(◕‿‿◕)'
BORED = '(-__-)'
INTENSE = '(°▃▃°)'
COOL = '(⌐■_■)'
HAPPY = '(•‿‿•)'
GRATEFUL = '(^‿‿^)'
EXCITED = '(ᵔ◡◡ᵔ)'
MOTIVATED = '(☼‿‿☼)'
DEMOTIVATED = '(≖__≖)'
SMART = '(✜‿‿✜)'
LONELY = '(ب__ب)'
SAD = '(╥☁╥ )'
ANGRY = "(-_-')"
FRIEND = '(♥‿‿♥)'
BROKEN = '(☓‿‿☓)'
DEBUG = '(#__#)'
UPLOAD = '(1__0)'
UPLOAD1 = '(1__1)'
UPLOAD2 = '(0__1)'

FACES = {"LOOK_R": LOOK_R,
         "LOOK_L": LOOK_L,
         "LOOK_R_HAPPY": LOOK_R_HAPPY,
         "LOOK_L_HAPPY": LOOK_L_HAPPY,
         "SLEEP": SLEEP,
         "SLEEP2": SLEEP2,
         "AWAKE": AWAKE,
         "BORED": BORED,
         "INTENSE": INTENSE,
         "COOL": COOL,
         "HAPPY": HAPPY,
         "GRATEFUL": GRATEFUL,
         "EXCITED": EXCITED,
         "MOTIVATED": MOTIVATED,
         "DEMOTIVATED": DEMOTIVATED,
         "SMART": SMART,
         "LONELY": LONELY,
         "SAD": SAD,
         "ANGRY": ANGRY,
         "FRIEND": FRIEND,
         "BROKEN": BROKEN,
         "DEBUG": DEBUG,
         "UPLOAD": UPLOAD,
         "UPLOAD1": UPLOAD1,
         "UPLOAD2": UPLOAD2,
         }


def to_rgb565(r, g, b):
    r = (r & 0b11111000) << 8
    g = (g & 0b11111100) << 3
    b = b >> 3
    val = r + g + b
    return val.to_bytes(2, 'big')


def im_to_raw(im):
    raw = []
    for y in range(im.height):
        for x in range(im.width):
            r, g, b = im.getpixel((x, y))
            raw.append(to_rgb565(r, g, b))
    return b''.join(raw)


unicode_font = ImageFont.truetype("DejaVuSans.ttf", 22)

sizes = [unicode_font.getsize(face) for face in FACES]
width = max([size[0] for size in sizes])
height = max([size[1] for size in sizes])

print(width, height)

out = Path("faces")
out.mkdir(exist_ok=True)

source = "/// This file is autogenerated\n\n"

source += f"pub const WIDTH: u32 = {width};\n"
source += f"pub const HEIGHT: u32 = {height};\n\n"

for name, face in FACES.items():
    im = Image.new("RGB", (width, height), (0, 0, 0))
    draw = ImageDraw.Draw(im)
    draw.text((0, 0), face, font=unicode_font, fill=(255, 255, 255))
    with open(out.joinpath(name), "wb") as fp:
        raw = im_to_raw(im)
        fp.write(raw)
    source += f"pub const {name}: &[u8] = include_bytes!(\"{name}\");\n"

with open(out.joinpath("mod.rs"), "w") as fp:
    fp.write(source)

